CREATE TABLE account
(
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    account     VARCHAR(255),
    email       VARCHAR(255),
    password    VARCHAR(255),
    status      SMALLINT                                 NOT NULL,
    employee_id INTEGER,
    CONSTRAINT pk_account PRIMARY KEY (id)
);

CREATE TABLE employee
(
    employee_id     INTEGER GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    first_name      VARCHAR(255),
    last_name       VARCHAR(255),
    gender          SMALLINT,
    date_of_birth   DATE,
    phone           VARCHAR(20),
    address         VARCHAR(255)                             NOT NULL,
    department_name VARCHAR(255),
    remark          VARCHAR(255)                             NOT NULL,
    CONSTRAINT pk_employee PRIMARY KEY (employee_id)
);

ALTER TABLE account
    ADD CONSTRAINT uc_account_account UNIQUE (account);

ALTER TABLE account
    ADD CONSTRAINT uc_account_email UNIQUE (email);

ALTER TABLE account
    ADD CONSTRAINT uc_account_employee UNIQUE (employee_id);

ALTER TABLE account
    ADD CONSTRAINT FK_ACCOUNT_ON_EMPLOYEE FOREIGN KEY (employee_id) REFERENCES employee (employee_id);